CREATE TABLE STORAGE(
ID NUMBER,
CONSTRAINT FILE_FK PRIMARY KEY(ID),
FORMAT_SUPPORTED NVARCHAR2(50) CHECK (FORMAT LIKE "txt" OR FORMAT LIKE "jpg"),
STORAGE_COUNTRY NVARCHAR2(50),
STORAGE_SIZE NUMBER,
)