CREATE TABLE FILES (
    ID NUMBER,
    CONSTRAINT FILES_PK PRIMARY KEY(ID),
    NAME NVARCHAR2(10) NOT NULL,
    FORMAT NVARCHAR2(20) NOT NULL,
    FILE_SIZE NUMBER,
    STORAGE_ID NUMBER NOT NULL,
    CONSTRAINT STORAGE_FK FOREIGN KEY(STORAGE_ID) REFERENCES STORAGE(ID)
);